---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Create User ans Group for forgejo runner
  ansible.builtin.include_tasks:
    file: 'create_user.yml'

- name: Set forgejo runner version
  ansible.builtin.include_tasks:
    file: 'set_runner_version.yml'

- name: Install forgejo runner binary
  ansible.builtin.include_tasks:
    file: 'install_runner.yml'

- name: Configure forgejo runner
  ansible.builtin.include_tasks:
    file: 'configure_runner.yml'

- name: Start forgejo runner as systemd service
  ansible.builtin.include_tasks:
    file: 'systemd.yml'
  when: ansible_service_mgr == "systemd"
