---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Create User ans Group for forgeo runner
  ansible.builtin.include_tasks:
    file: 'create_user.yml'
