---
- name: "Setup systemd service"
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.template:
    src: 'forgejo_runner.service.j2'
    dest: '/lib/systemd/system/forgejo-runner.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'systemctl restart forgejo-runner'
    - 'systemctl daemon-reload'

- name: "Reload systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  notify: 'systemctl restart forgejo-runner'

- name: "Start and enable forgejo-runner"
  become: true
  ansible.builtin.systemd:
    name: 'forgejo-runner'
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"
  notify: 'systemctl restart forgejo-runner'
